/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NewImport } from './routes/new'
import { Route as UserIdImport } from './routes/$userId'
import { Route as IndexImport } from './routes/index'
import { Route as UsersUserIdEditImport } from './routes/users.$userId.edit'

// Create/Update Routes

const NewRoute = NewImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRoute,
} as any)

const UserIdRoute = UserIdImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UsersUserIdEditRoute = UsersUserIdEditImport.update({
  id: '/users/$userId/edit',
  path: '/users/$userId/edit',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$userId': {
      id: '/$userId'
      path: '/$userId'
      fullPath: '/$userId'
      preLoaderRoute: typeof UserIdImport
      parentRoute: typeof rootRoute
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewImport
      parentRoute: typeof rootRoute
    }
    '/users/$userId/edit': {
      id: '/users/$userId/edit'
      path: '/users/$userId/edit'
      fullPath: '/users/$userId/edit'
      preLoaderRoute: typeof UsersUserIdEditImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$userId': typeof UserIdRoute
  '/new': typeof NewRoute
  '/users/$userId/edit': typeof UsersUserIdEditRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$userId': typeof UserIdRoute
  '/new': typeof NewRoute
  '/users/$userId/edit': typeof UsersUserIdEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$userId': typeof UserIdRoute
  '/new': typeof NewRoute
  '/users/$userId/edit': typeof UsersUserIdEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$userId' | '/new' | '/users/$userId/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$userId' | '/new' | '/users/$userId/edit'
  id: '__root__' | '/' | '/$userId' | '/new' | '/users/$userId/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UserIdRoute: typeof UserIdRoute
  NewRoute: typeof NewRoute
  UsersUserIdEditRoute: typeof UsersUserIdEditRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UserIdRoute: UserIdRoute,
  NewRoute: NewRoute,
  UsersUserIdEditRoute: UsersUserIdEditRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$userId",
        "/new",
        "/users/$userId/edit"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$userId": {
      "filePath": "$userId.tsx"
    },
    "/new": {
      "filePath": "new.tsx"
    },
    "/users/$userId/edit": {
      "filePath": "users.$userId.edit.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
